### ISSUE TITLE
run fails with SSH Enabled Zyxel GS1900-24EP

### ISSUE THREAD

**Issue by DirectorSloan** [andrewjw/zyxelprometheus#12]
1. Build the virtualenv && activated it
2. run `bash buildbot.sh` in venv
3. run `python setup.py install` in venv

Python Version is `3.8.7`

**Error Output:**
```
(zyxelprometheus-venv) network@host ~/zyxelprometheus $ zyxelprometheus --host myIP --user myUSer --passwd myPassword
Traceback (most recent call last):
  File "/home/network/zyxelprometheus-venv/bin/zyxelprometheus", line 4, in <module>
    __import__('pkg_resources').run_script('zyxelprometheus==0.5.5', 'zyxelprometheus')
  File "/home/network/zyxelprometheus-venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/network/zyxelprometheus-venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/home/network/zyxelprometheus-venv/lib/python3.8/site-packages/zyxelprometheus-0.5.5-py3.8.egg/EGG-INFO/scripts/zyxelprometheus", line 48, in <module>
  File "/home/network/zyxelprometheus-venv/lib/python3.8/site-packages/zyxelprometheus-0.5.5-py3.8.egg/EGG-INFO/scripts/zyxelprometheus", line 43, in main
  File "/home/network/zyxelprometheus-venv/lib/python3.8/site-packages/zyxelprometheus-0.5.5-py3.8.egg/zyxelprometheus/prometheus.py", line 64, in prometheus
AttributeError: 'NoneType' object has no attribute 'group'
```

Any help will be appreciated.

**Comment by andrewjw** [comment]
Hi,

Thanks for the bug report! I only have one model, so I think your model returns different output to the commands that are run.

Can you manually ssh in and share the output for `xdslctl info` and `ifconfig`? We should then be able to update the code to work for both models.

Cheers,
Andrew
